version: '3.9'

services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    restart: unless-stopped
    command: --config /livekit.yaml
    ports:
      - '7880:7880'
      - '7881:7881'
      - '3478:3478/udp'
      - '5349:5349/tcp'
      - '50000-60000:50000-60000/udp'
    volumes:
      - ./livekit.config.yaml:/livekit.yaml
    env_file:
      - .env

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    depends_on:
      - livekit

volumes:
  caddy_data:
  caddy_config:
